import { Schibsted_Grotesk, Merriweather, Nosifer } from "next/font/google";
import "./globals.css";

const grostesk = Schibsted_Grotesk({
  variable: "--font-grostesk",
  weight: "400",
  subsets: ["latin"],
});
const merriweather = Merriweather({
  variable: "--font-merriweather",
  weight: "400",
  subsets: ["latin"],
});

const NosiferFont = Nosifer({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-nosifer",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${grostesk.variable} ${merriweather.variable} ${NosiferFont.variable} antialiased font-secondary `}
      >
        {children}
      </body>
    </html>
  );
}
