import Naviagation from "@/components/Naviagation";
import {
  Merriweather,
  Nosifer,
  Playfair_Display,
  Barlow_Semi_Condensed,
} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { ThemeProvider } from "next-themes";
const Playfair = Playfair_Display({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-playfair",
});
const Barlow = Barlow_Semi_Condensed({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-barlow",
});
const merriweather = Merriweather({
  variable: "--font-merriweather",
  weight: "400",
  subsets: ["latin"],
});

const NosiferFont = Nosifer({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-nosifer",
});

export const metadata = {
  title: "Luqman Muhammed | Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${merriweather.variable} ${Barlow.variable} ${NosiferFont.variable} ${Playfair.variable} text-secondary font-merri bg-primary overflow-x-hidden antialiased`}
      >
        <ThemeProvider
          attribute="data-theme"
          defaultTheme="system"
          enableSystem
        >
          <Naviagation />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
